services:
  postgres:
    container_name: nest_clean_postgres
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest_clean
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
